### ISSUE TITLE
require "prawn/gmagick" fails on ruby 3.0

### ISSUE THREAD

**Issue by branic** [packetmonkey/prawn-gmagick#20]
I'm trying to use this gem on a system that has Ruby 3.0 installed, but when Ruby tries to load the library via the `require "prawn/gmagick'` statement it fails with:

```
/usr/local/share/gems/gems/prawn-gmagick-0.0.9/lib/prawn/gmagick.rb:2:in `require_relative': libruby-2.2.so.2.2: cannot open shared object file: No such file or directory - /usr/local/share/gems/gems/prawn-gmagick-0.0.9/lib/image.so (LoadError)
	from /usr/local/share/gems/gems/prawn-gmagick-0.0.9/lib/prawn/gmagick.rb:2:in `<top (required)>'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:160:in `require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:149:in `require'
	from /home/work/test.rb:3:in `<main>'
<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- prawn/gmagick (LoadError)
	from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/work/test.rb:3:in `<main>'
```

The ruby version is:

```
bash-4.4$ ruby --version
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
```

Looking at the dynamic dependencies of `/usr/local/share/gems/gems/prawn-gmagick-0.0.9/lib/image.so` reveals that it somehow linked against the Ruby 2.2 version of `libruby` (and is linked against libGraphicsMagickWand and libGraphicsMagick libraries that do not exist):

```
bash-4.4$ ldd /usr/local/share/gems/gems/prawn-gmagick-0.0.9/lib/image.so
	linux-vdso.so.1 (0x00007fff6e1a5000)
	libruby-2.2.so.2.2 => not found
	libGraphicsMagickWand.so.2 => not found
	libGraphicsMagick.so.3 => not found
	libc.so.6 => /lib64/libc.so.6 (0x00007f1f11000000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1f11800000)
```

There are 3 copies of the `image.so` library on the system after the `prawn-gmagick` install:

```
bash-4.4$ find / -name 'image.so'
/usr/local/share/gems/gems/prawn-gmagick-0.0.9/lib/image.so
/usr/local/share/gems/gems/prawn-gmagick-0.0.9/ext/image/image.so
/usr/local/lib64/gems/ruby/prawn-gmagick-0.0.9/image.so
```

Looking at the other two versions of the `image.so` library  reveal that they are linked correctly to require the `libruby-3.0` library (they also are correctly linked against the correct libGraphicsMagickWand and libGraphicsMagick libraries):

```
bash-4.4$ ldd /usr/local/share/gems/gems/prawn-gmagick-0.0.9/ext/image/image.so
	linux-vdso.so.1 (0x00007fff38f9b000)
	libruby.so.3.0 => /lib64/libruby.so.3.0 (0x00007fc1f4800000)
	libGraphicsMagickWand-Q16.so.2 => /lib64/libGraphicsMagickWand-Q16.so.2 (0x00007fc1f4400000)
	libGraphicsMagick-Q16.so.3 => /lib64/libGraphicsMagick-Q16.so.3 (0x00007fc1f4000000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fc1f3c00000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fc1f3800000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fc1f3400000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc1f3000000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fc1f2c00000)
	libgmp.so.10 => /lib64/libgmp.so.10 (0x00007fc1f2800000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fc1f2400000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007fc1f2000000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc1f5200000)
	liblcms2.so.2 => /lib64/liblcms2.so.2 (0x00007fc1f1c00000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007fc1f1800000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007fc1f1400000)
	libSM.so.6 => /lib64/libSM.so.6 (0x00007fc1f1000000)
	libICE.so.6 => /lib64/libICE.so.6 (0x00007fc1f0c00000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007fc1f0800000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007fc1f0400000)
	libltdl.so.7 => /lib64/libltdl.so.7 (0x00007fc1f0000000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00007fc1efc00000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fc1ef800000)
	libpng16.so.16 => /lib64/libpng16.so.16 (0x00007fc1ef400000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007fc1ef000000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007fc1eec00000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007fc1ee800000)
```

```
bash-4.4$ ldd /usr/local/lib64/gems/ruby/prawn-gmagick-0.0.9/image.so
	linux-vdso.so.1 (0x00007ffc31ff9000)
	libruby.so.3.0 => /lib64/libruby.so.3.0 (0x00007fc82a600000)
	libGraphicsMagickWand-Q16.so.2 => /lib64/libGraphicsMagickWand-Q16.so.2 (0x00007fc82a200000)
	libGraphicsMagick-Q16.so.3 => /lib64/libGraphicsMagick-Q16.so.3 (0x00007fc829e00000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fc829a00000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fc829600000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fc829200000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc828e00000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fc828a00000)
	libgmp.so.10 => /lib64/libgmp.so.10 (0x00007fc828600000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fc828200000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007fc827e00000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc82b000000)
	liblcms2.so.2 => /lib64/liblcms2.so.2 (0x00007fc827a00000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007fc827600000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007fc827200000)
	libSM.so.6 => /lib64/libSM.so.6 (0x00007fc826e00000)
	libICE.so.6 => /lib64/libICE.so.6 (0x00007fc826a00000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007fc826600000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007fc826200000)
	libltdl.so.7 => /lib64/libltdl.so.7 (0x00007fc825e00000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00007fc825a00000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fc825600000)
	libpng16.so.16 => /lib64/libpng16.so.16 (0x00007fc825200000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007fc824e00000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007fc824a00000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007fc824600000)
```

This example Dockerfile will build a simple container that reproduces the problem:

```
FROM registry.access.redhat.com/ubi8:latest

USER root

RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm

RUN dnf -y module enable ruby:3.0 && \
    dnf -y module install ruby:3.0

RUN dnf -y install \
        gcc \
        make \
        ruby-devel \
        GraphicsMagick-devel

RUN gem install --no-document prawn-gmagick

RUN mkdir /home/work && \
    printf '#! /bin/env ruby\n \
            \n \
            require "prawn/gmagick"\n \
           ' >> /home/work/test.rb \
    chgrp -R 0 /home/work && \
    chmod -R g=u /home/work && \
    chmod a+x /home/work/test.rb

ENV HOME=/home/work

USER 1001

CMD ["/home/work/test.rb"]
```

**Comment by boydkelly** [comment]
Not sure if this is related, but I'm trying to use asciidoctor-pdf on Fedora.   ImageMagick and Graphics-Magick are installed but even when prawn-gmagick is installed it seems that asciidoctor-pdf cannot find the Gem.

````
ruby -version
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

 /usr/local/bin/asciidoctor-pdf --version
Asciidoctor PDF 2.3.0 using Asciidoctor 2.0.17 [https://asciidoctor.org]
Runtime Environment (ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
 gem install prawn-gmagick
Building native extensions. This could take a while...
Successfully installed prawn-gmagick-0.0.9
Parsing documentation for prawn-gmagick-0.0.9
Done installing documentation for prawn-gmagick after 0 seconds
1 gem installed
 bkelly  toolbox  ~  dev  antora  assembler-tutorial  docs-site  main  1✎  1+  $  /usr/local/bin/asciidoctor-pdf demo-component-a/modules/ROOT/pages/udhr.adoc 
asciidoctor: WARNING: could not embed image: /var/home/bkelly/dev/antora/assembler-tutorial/docs-site/demo-component-a/modules/ROOT/pages/udhr.webp; image file is an unrecognised format; install prawn-gmagick gem to add support for WEBP image format
asciidoctor: WARNING: could not embed image: /var/home/bkelly/dev/antora/assembler-tutorial/docs-site/demo-component-a/modules/ROOT/pages/udhr.webp; image file is an unrecognised format; install prawn-gmagick gem to add support for WEBP image format

**Comment by ferrao** [comment]
It's 2025 and I this issue is still present, anybody has a quick workaround for this?

**Comment by ferrao** [comment]
Got it! In case anyone comes across the same problem, these are my steps to fix the issue:

```
git clone git@github.com:packetmonkey/prawn-gmagick.git
cd prawn-gmagick
ruby ext/image/extconf.rb
make
cp image.so ~/.local/share/gem/ruby/3.3.0/gems/prawn-gmagick-0.0.9/lib
```

You can make sure the compiled `image.so` is loading the appropriate ruby lib with ` ldd image.so | grep ruby` and to test that all is working:

```
ruby -e "require 'prawn/gmagick'; puts GMagick::Image"\n
```
